@secret = 

POST https://graphql.us.fauna.com/graphql
Content-Type: application/json
Authorization: Bearer {{secret}}
X-REQUEST-TYPE: GraphQL

query {
  getAllSkills {
    data {
      _id
      title
      details
      icon
    }
  }
}